services:
    akeneo.pim.structure.query.get_existing_attribute_option_codes_from_option_codes:
        class: 'Akeneo\Pim\Structure\Bundle\Query\PublicApi\AttributeOption\Sql\GetExistingAttributeOptionCodes'
        arguments:
            $connection: '@database_connection'

    akeneo.pim.structure.query.get_attribute_by_codes:
        class: 'Akeneo\Pim\Structure\Bundle\Query\PublicApi\AttributeTypes\Sql\SqlGetAttributeByCodes'
        arguments:
            $connection: '@database_connection'
